from __future__ import annotations

import json
from pathlib import Path

from .artifacts import slugify
from .models import RoleArtifact


def build_frontend_delivery(
    frontend_dir: Path,
    *,
    product_request: str,
    ba_content: str,
    backend_content: str,
) -> RoleArtifact:
    target_dir = frontend_dir / "app" / "generated"
    target_dir.mkdir(parents=True, exist_ok=True)
    page_file = target_dir / "page.tsx"
    meta_file = target_dir / "delivery.json"

    feature_name = slugify(product_request)
    page_source = _page_template(product_request, ba_content, backend_content)
    page_file.write_text(page_source, encoding="utf-8")

    payload = {
        "feature": feature_name,
        "route": "/generated",
        "request": product_request,
        "artifacts": {
            "business": "shared/outputs/<run_id>/ba.md",
            "backend": "shared/outputs/<run_id>/backend.md",
        },
        "files": [str(page_file)],
    }
    meta_file.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    changelog = "\n".join(
        [
            "# Frontend Delivery",
            "",
            f"- Generated route: `/generated`",
            f"- Feature slug: `{feature_name}`",
            "- Added a production-oriented dashboard page using App Router",
            "- Wired sections for business scope, API plan, and release checklist handoff",
        ]
    )
    return RoleArtifact(
        role="Frontend",
        title="Frontend Delivery",
        content=changelog,
        summary="Generated a production-ready dashboard route in the Next.js app.",
        path=str(page_file),
    )


def _page_template(product_request: str, ba_content: str, backend_content: str) -> str:
    sanitized_ba = _to_lines(ba_content)
    sanitized_backend = _to_lines(backend_content)
    return f"""import Link from "next/link";

const businessHighlights = {json.dumps(sanitized_ba, indent=2)} as const;
const backendHighlights = {json.dumps(sanitized_backend, indent=2)} as const;

function BulletList({{
  title,
  items,
}}: {{
  title: string;
  items: readonly string[];
}}) {{
  return (
    <section className="rounded-[28px] border border-black/10 bg-white p-6 shadow-[0_20px_60px_rgba(15,23,42,0.08)]">
      <p className="text-sm font-semibold uppercase tracking-[0.18em] text-slate-500">{{title}}</p>
      <ul className="mt-4 space-y-3 text-sm leading-6 text-slate-700">
        {{items.map((item) => (
          <li key={{item}} className="rounded-2xl bg-slate-50 px-4 py-3">
            {{item}}
          </li>
        ))}}
      </ul>
    </section>
  );
}}

export default function GeneratedFeaturePage() {{
  return (
    <main className="min-h-screen bg-[radial-gradient(circle_at_top,_#fef3c7,_#f8fafc_42%,_#e0f2fe)] px-6 py-10 text-slate-950">
      <div className="mx-auto max-w-6xl">
        <div className="grid gap-6 lg:grid-cols-[1.35fr_0.65fr]">
          <section className="rounded-[32px] bg-slate-950 px-8 py-10 text-white shadow-[0_24px_80px_rgba(15,23,42,0.28)]">
            <p className="text-sm uppercase tracking-[0.3em] text-amber-300">Production Delivery</p>
            <h1 className="mt-4 max-w-2xl text-4xl font-semibold leading-tight sm:text-5xl">
              {product_request}
            </h1>
            <p className="mt-5 max-w-2xl text-base leading-7 text-slate-200">
              This route is generated by the IT Department crew as the current production-ready frontend
              delivery surface. It centralizes business intent, backend integration planning, and QA
              handoff in one implementation entrypoint.
            </p>
            <div className="mt-8 flex flex-wrap gap-3 text-sm">
              <span className="rounded-full bg-white/10 px-4 py-2">Next.js App Router</span>
              <span className="rounded-full bg-white/10 px-4 py-2">TypeScript</span>
              <span className="rounded-full bg-white/10 px-4 py-2">Crew-delivered</span>
            </div>
            <div className="mt-8">
              <Link
                href="/"
                className="inline-flex items-center rounded-full bg-amber-300 px-5 py-3 text-sm font-semibold text-slate-950 transition hover:bg-amber-200"
              >
                Return to command center
              </Link>
            </div>
          </section>
          <section className="rounded-[32px] border border-black/10 bg-white/80 p-6 backdrop-blur">
            <p className="text-sm font-semibold uppercase tracking-[0.18em] text-slate-500">Release intent</p>
            <div className="mt-5 grid gap-4">
              <div className="rounded-2xl bg-amber-50 p-5">
                <p className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-700">Primary route</p>
                <p className="mt-2 text-2xl font-semibold text-slate-950">/generated</p>
              </div>
              <div className="rounded-2xl bg-slate-100 p-5">
                <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Delivery policy</p>
                <p className="mt-2 text-sm leading-6 text-slate-700">
                  Keep future crew-generated UI changes isolated under <code>app/generated</code> or
                  extracted shared components.
                </p>
              </div>
            </div>
          </section>
        </div>

        <div className="mt-8 grid gap-6 lg:grid-cols-2">
          <BulletList title="Business highlights" items={{businessHighlights}} />
          <BulletList title="Backend highlights" items={{backendHighlights}} />
        </div>
      </div>
    </main>
  );
}}
"""


def _to_lines(raw: str) -> list[str]:
    lines = [line.strip("- ").strip() for line in raw.splitlines() if line.strip()]
    if not lines:
        return ["No structured content was generated for this section yet."]
    return lines[:6]
